apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}-service
spec:
  type: NodePort
  selector:
    app: {{ .Values.backend.name }}
  ports:
  - port: {{ .Values.backend.servicePort }}
    targetPort: {{ .Values.backend.containerPort }}