frontend:
  name: frontend
  image:
  repository: srayudu/ms-demorepo
  tag: frontend-6d7f1c3
  replicas: 2
  containerPort: 3000
  servicePort: 80

backend:
  name: backend
  image:
  repository: srayudu/ms-demorepo
  tag: frontend-6d7f1c3
  replicas: 2
  containerPort: 5000
  servicePort: 80

ingress:
  enabled: true
  host: app.local