name: Deploy App to Azure App Service

on:
  push:
    branches:
      - appservice

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # 🔥 Azure Login (OIDC)
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      # 🔹 Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 🔹 Install dependencies
      - name: Install Dependencies
        working-directory: application
        run: npm install

      # 🔹 Deploy to App Service
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          package: .