name: Build Java Artifact

on:
  push:
    branches:
      - aks-branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: java-app-artifact
        path: target/*.jar