name: Build Docker Image

#on:
 # push:
    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker Image
      working-directory: azure_aks-cluster/Application-test-java
      run: |
        docker build -t java-app:${{ github.sha }} .